#---------------------------------#
#      environment configuration  #
#---------------------------------#
os: Unstable
version: 0.1.{build}.0
install:
  - cinst -y pester
  - ps: |
      Invoke-WebRequest -Uri 'https://oneget.org/nuget-anycpu-2.8.3.6.exe' -OutFile 'C:\Program Files\PackageManagement\ProviderAssemblies\nuget-anycpu.exe'
      if (!(test-path "$env:ProgramFiles\PackageManagement\ProviderAssemblies") {mkdir "$env:ProgramFiles\PackageManagement\ProviderAssemblies"}
  
environment:
  APIKEY:
    secure: Ne1LPTeW3a/X9oC7CRnEitE+vNfGssb1rnaP8Uq74/HHGbZ5XkqLg/IQKRdDGnlm

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        $testResultsFile = ".\TestsResults.xml"
        $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        if ($res.FailedCount -gt 0) {
            throw "$($res.FailedCount) tests failed."
        }

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment

# NOTE The manifest file should be dynamically identified, as should the module version data in the file
before_deploy:
  - ps: |
      # Update Manifest File
      $stagingDirectory = (Resolve-Path ..).Path
      $manifest = Join-Path $pwd 'WSManTrust.psd1'
      (Get-Content $manifest -Raw).Replace("0.1.0.0", $env:APPVEYOR_BUILD_VERSION) | Out-File $manifest

#---------------------------------#
#      after build                #
#---------------------------------#

on_finish:
- ps: #$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_success:
  - ps: Publish-Module -NuGetAPIKey $env:APIKEY -Path $pwd -whatif